name: version_check
description: Check iOS/Android/Mac store version and provide update alert if update is available.
version: 0.4.0
#author: ChunKoo Park <mix1009@gmail.com>
homepage: https://github.com/mix1009/version_check

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^5.0.1
  http: ^0.13.6
  html: ^0.15.3
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
